set(_AMENT_PACKAGE_NAME "findgate")
set(findgate_VERSION "0.0.0")
set(findgate_MAINTAINER "mohamedmehery <es-mohamed.abdelnasser1415@alexu.edu.eg>")
set(findgate_BUILD_DEPENDS )
set(findgate_BUILDTOOL_DEPENDS "ament_cmake")
set(findgate_BUILD_EXPORT_DEPENDS )
set(findgate_BUILDTOOL_EXPORT_DEPENDS )
set(findgate_EXEC_DEPENDS )
set(findgate_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(findgate_GROUP_DEPENDS )
set(findgate_MEMBER_OF_GROUPS )
set(findgate_DEPRECATED "")
set(findgate_EXPORT_TAGS)
list(APPEND findgate_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
